spring:
  # Database Configuration
  datasource:
    url: jdbc:h2:mem:collab_docs
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api

# JWT Configuration
app:
  jwt:
    secret: your-256-bit-secret-key-for-jwt-token-signing-and-verification
    expiration: 86400000 # 24 hours in milliseconds

# WebSocket Configuration
websocket:
  endpoint: /ws
  allowed-origins: "*"
  
# Logging Configuration
logging:
  level:
    root: INFO
    com.collab.docs: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.web.socket: DEBUG
